# baseURL
@baseURL = http://localhost:3000

###
# Find All Visite
POST {{ baseURL }}/Visites
###
# Find All Antecedants
POST {{ baseURL }}/Antecedants

###
# Create Visite
POST {{ baseURL }}/VisitesCreate
Content-Type: application/json

{
    "id": 200,
	"Medecin": "Ayoub"
}

###
# Create Antecedants
POST {{ baseURL }}/AntecedantsCreate
{
    "id": 200,
	"Medcin": "Yacine",
    "Maladie":"Entorse"
}
